### ISSUE TITLE
not an issue i love the mod but please could you try to also add this as an option

### ISSUE THREAD

**Issue by hqcked** [flurrybun/blending-glow#1]
if its not too much to ask please could you try to add a setting that enables whatever made the darker colors have brighter glow in 2.1? 
![image](https://github.com/flurrybun/blending-glow/assets/42199661/a7ff63a8-5ad5-4368-8e8f-11c6534fe933) 
![image](https://github.com/flurrybun/blending-glow/assets/42199661/a2b34dd1-c8a4-4a24-81e0-eab40267a81a)

**Comment by flurrybun** [comment]
sure. shouldn't take too long

**Comment by flurrybun** [comment]
added as an option in the latest release. it only works in levels and not in the menus like you showed, but i think that's probably good enough

new version should be on the geode index soon

**Comment by hqcked** [comment]
tysm
